extends TestCase
## The sprite maker's shopping list (D-138): plan a wide sweep of towns with the real planner, count
## what actually appears and how often, and write the build list to user:// as markdown (for a
## person) and JSON (for a pipeline). Regenerate after any catalogue change rather than hand-editing.
##
## The frequencies are the point: the list tells the sprite maker what to draw first, because it is
## the order the game will actually ask for the pieces in.

const SEED := 5150
const KINDS := ["village", "town", "fort", "castle"]
const TOWNS_PER_KIND := 40
const MARKDOWN_PATH := "user://sprite_list.md"
const JSON_PATH := "user://sprite_list.json"


func run() -> void:
	await _tick()
	_sweep()
	_write_list()
	_complete()


var _towns := 0
var _type_stats := {}
var _attachment_stats := {}
var _biome_stats := {}
var _purpose_stats := {}
var _condition_stats := {}


func _sweep() -> void:
	for kind in KINDS:
		for i in TOWNS_PER_KIND:
			var s := Settlement.new()
			s.id = "sweep_%s_%d" % [kind, i]
			s.name = s.id.capitalize()
			s.type = kind
			s.owner_faction_id = "house_caldreth"
			s.population = 250 + i * 60
			s.position = Vector2(300.0 + float((i * 977) % 4200), 300.0 + float((i * 613) % 3800))
			SettlementDetails.fill(s, SEED)
			_towns += 1
			_biome_stats[s.biome] = int(_biome_stats.get(s.biome, 0)) + 1
			var purpose := SettlementBuildings.purpose_for(s.type, s.biome, s.wealth)
			_purpose_stats[purpose] = int(_purpose_stats.get(purpose, 0)) + 1
			for entry in s.buildings:
				var info: Dictionary = entry as Dictionary
				var id := str(info.get("id", ""))
				var stats: Dictionary = _type_stats.get(id, {
					"towns": 0, "roofs": {}, "walls": {}, "conditions": {}, "name": info.get("name", ""),
					"category": info.get("category", ""),
				})
				stats["towns"] = int(stats["towns"]) + 1
				(stats["roofs"] as Dictionary)[str(info.get("roof", ""))] = true
				(stats["walls"] as Dictionary)[str(info.get("wall", ""))] = true
				(stats["conditions"] as Dictionary)[str(info.get("condition", ""))] = true
				_type_stats[id] = stats
				_condition_stats[str(info.get("condition", ""))] = \
					int(_condition_stats.get(str(info.get("condition", "")), 0)) + 1
				for attachment in (info.get("attachments", []) as Array):
					_attachment_stats[str(attachment)] = int(_attachment_stats.get(str(attachment), 0)) + 1


func _ranked(stats: Dictionary) -> Array:
	var ids: Array = stats.keys()
	ids.sort_custom(func(a, b): return int((stats[a] as Dictionary)["towns"]) > int((stats[b] as Dictionary)["towns"]))
	return ids


func _write_list() -> void:
	var lines: Array[String] = []
	lines.append("# Project Banner — settlement sprite list")
	lines.append("")
	lines.append("Generated by `tests/test_sprite_list.gd` from the building catalogue (D-138): %d towns" % _towns)
	lines.append("planned with the real generator, every appearance counted. Regenerate rather than hand-edit.")
	lines.append("")
	lines.append("**Style (the owner's art direction):** crisp pixel art, strong dark outlines, readable")
	lines.append("silhouette, isometric / elevated perspective, grounded medieval look, slightly stylized")
	lines.append("proportions, one consistent light direction, controlled palette, clear roofs, clear timber")
	lines.append("framing. Avoid: overly clean repetition, generic fantasy exaggeration, excess gold,")
	lines.append("identical proportions, visual noise, details that vanish at gameplay scale.")
	lines.append("**Rule of the programme:** the system comes first. Draw bases + one material set + one")
	lines.append("condition overlay first; the breadth (every biome, every attachment) is a later pass.")
	lines.append("")
	lines.append("**Budgets over these %d towns** — grounds: %s · purposes: %s" % [
		_towns, _flat(_biome_stats), _flat(_purpose_stats)])
	lines.append("")

	lines.append("## Draw order — every building base, most-used first")
	lines.append("")
	lines.append("| # | Building | Category | Towns (of %d) | Conditions seen | Roofs seen | Walls seen |" % _towns)
	lines.append("|---|----------|----------|---------------|-----------------|------------|------------|")
	var rank := 0
	var order: Array[String] = []
	for id in _ranked(_type_stats):
		rank += 1
		order.append(id)
		var stats: Dictionary = _type_stats[id] as Dictionary
		lines.append("| %d | %s (`%s`) | %s | %d | %s | %s | %s |" % [
			rank, str(stats["name"]), id, str(stats["category"]), int(stats["towns"]),
			_flat(stats["conditions"] as Dictionary), _flat(stats["roofs"] as Dictionary),
			_flat(stats["walls"] as Dictionary)])
	lines.append("")

	lines.append("## Attachment pieces — the modules stacked around buildings")
	lines.append("")
	lines.append("| Attachment | Times placed (of %d towns) |" % _towns)
	lines.append("|------------|---------------------------|")
	var attachments := SettlementBuildings.catalogue().get("attachments", []) as Array
	var families := {"structural": "Structural", "clutter": "Clutter", "life": "Life / detail"}
	for family in ["structural", "clutter", "life"]:
		lines.append("")
		lines.append("### %s" % families[family])
		lines.append("")
		for entry in attachments:
			var row: Dictionary = entry as Dictionary
			if str(row.get("kind", "")) != family:
				continue
			var id := str(row.get("id", ""))
			lines.append("- **%s** (`%s`) — %d placements" % [
				str(row.get("name", "")), id, int(_attachment_stats.get(id, 0))])
	lines.append("")

	lines.append("## Condition states — overlays, one set per state")
	lines.append("")
	lines.append("Rolled per building from the settlement's wealth. Draw as overlays so a base is drawn once:")
	lines.append("")
	for condition in ["poor", "average", "damaged", "abandoned", "repaired", "wealthy"]:
		lines.append("- **%s** — %d buildings in the sweep" % [
			condition, int(_condition_stats.get(condition, 0))])
	lines.append("")

	lines.append("## Materials — roofs and walls by ground")
	lines.append("")
	var materials: Dictionary = SettlementBuildings.catalogue().get("materials", {}) as Dictionary
	for biome in materials.keys():
		var row: Dictionary = materials[biome] as Dictionary
		lines.append("- **%s** — roofs: %s | walls: %s" % [
			str(biome), ", ".join(row.get("roofs", []) as Array),
			", ".join(row.get("walls", []) as Array)])
	lines.append("")

	var total_bases := _type_stats.size()
	var total_attachments := (SettlementBuildings.catalogue().get("attachments", []) as Array).size()
	lines.append("## The count")
	lines.append("")
	lines.append("- %d building bases drawn in this sweep (of %d in the catalogue)" % [
		total_bases, SettlementBuildings.types().size()])
	lines.append("- %d attachment modules" % total_attachments)
	lines.append("- 6 condition overlays + 5 detail toggles (chimney, clutter, sign, fence, garden)")
	lines.append("- materials: roofs and walls as listed per ground (deduplicated across grounds)")
	lines.append("")

	var markdown := "\n".join(lines)
	var file := FileAccess.open(MARKDOWN_PATH, FileAccess.WRITE)
	if file != null:
		file.store_string(markdown)
		file.close()
		print("sprite list written: %s" % ProjectSettings.globalize_path(MARKDOWN_PATH))
	else:
		print("sprite list: could not write %s" % MARKDOWN_PATH)

	# The pipeline copy: the same counts, for a machine to read.
	var payload := {
		"towns": _towns,
		"types": _type_stats,
		"attachments": _attachment_stats,
		"biomes": _biome_stats,
		"purposes": _purpose_stats,
		"conditions": _condition_stats,
	}
	var json_file := FileAccess.open(JSON_PATH, FileAccess.WRITE)
	if json_file != null:
		json_file.store_string(JSON.stringify(payload, "  "))
		json_file.close()

	print("sprite list: top ten: %s" % ", ".join(order.slice(0, 10)))
	check(_type_stats.size() > 20, "the sweep builds enough variety to rank the list")
	check(FileAccess.file_exists(MARKDOWN_PATH), "and the list is on disk")


func _flat(counts: Dictionary) -> String:
	var keys: Array = counts.keys()
	var parts: Array[String] = []
	for key in keys:
		parts.append("%s x%d" % [str(key), int(counts[key])] if counts[key] is int else str(key))
	return ", ".join(parts) if not parts.is_empty() else "-"
