class_name WorldBuilder
extends RefCounted
## Turns the settlement data files into live [Settlement] records on a campaign.
##
## Idempotent by design: [method build_if_needed] only builds when the campaign
## has no settlements, so loading a save keeps the saved world state (visited
## flags, depleted recruit pools, later on faction ownership) while a fresh
## campaign gets the authored starting region.

const SETTLEMENTS_PATH := "res://data/settlements/settlements.json"

var state: CampaignState
var config: GameConfig


func _init(p_state: CampaignState, p_config: GameConfig) -> void:
	state = p_state
	config = p_config


## Returns true when the world was built, false when it already existed.
## Whether this campaign has a world yet. The map asks before it shows a loading screen, so a loaded
## save does not flash one for a build that will not happen.
func needs_build() -> bool:
	return state != null and state.settlements.is_empty()


func build_if_needed() -> bool:
	if state == null:
		return false
	if not state.settlements.is_empty():
		return false
	build()
	return true


## How far the build has got, 0.0 to 1.0, written inside the loop below and read by the loading
## screen on the main thread. A float written by one thread and read by another is not a contract, but
## it is a number that is always either the previous count or the current one, which for a progress bar
## is exactly enough. The owner's words: "loading bar isn't accurate it gets to about %90 and then
## pauses, then the game loads" - it paused because it was guessing, and now it does not have to.
var progress := 0.0

## How many settlements exist. The loop below places one per iteration.
var placing := 0

## What the build is doing, in the owner's language, for the loading screen to show. He asked for more
## of these, and the honest ones are the stages that really exist - a message per phase, not a rotation
## of flavour text invented to fill time.
var stage := "Reading the seed"


func build() -> void:
	if state == null:
		return
	state.settlements.clear()
	state.roads.clear()
	var phase_started := Time.get_ticks_usec()

	# Generated by default: the land proposes the sites and the seed settles what they are. The
	# authored file remains one config value away - a known map is still the right thing for a test
	# that wants to assert about Greywatch by name.
	if config != null and config.get_bool("world.procedural", true):
		_build_procedural()
		DebugLogger.info("  build total: %.0f ms" % [float(Time.get_ticks_usec() - phase_started) / 1000.0], "WorldBuilder")
		return

	var data := GameData.load_json(SETTLEMENTS_PATH)
	for raw in data.get("settlements", []) as Array:
		if typeof(raw) != TYPE_DICTIONARY:
			continue
		var settlement := _build_settlement(raw as Dictionary)
		if settlement == null:
			continue
		state.settlements[settlement.id] = settlement

	for raw_road in data.get("roads", []) as Array:
		if typeof(raw_road) != TYPE_DICTIONARY:
			continue
		var road := raw_road as Dictionary
		var a := str(road.get("a", ""))
		var b := str(road.get("b", ""))
		if a.is_empty() or b.is_empty():
			continue
		if not state.settlements.has(a) or not state.settlements.has(b):
			DebugLogger.warn("road references unknown settlement (%s -> %s)" % [a, b], "WorldBuilder")
			continue
		state.roads.append({
			"a": a,
			"b": b,
			"kind": str(road.get("kind", "road")),
		})

	_place_player_party()
	DebugLogger.info("world built: %d settlements, %d roads" % [
		state.settlements.size(), state.roads.size(),
	], "WorldBuilder")


## The world, generated: sites from the land, names from the sites, roads between them.
func _build_procedural() -> void:
	var seed_value := int(state.campaign_seed)
	var count := config.get_int("world.settlement_count", 14)
	var radius := config.get_float("world.settlement_search_radius", 2900.0)
	# The middle of the campaign's map, because the world is drawn as one map today; when the map
	# becomes a window on a bigger world, this becomes wherever the campaign began.
	# The middle of the world, and a radius that reaches its corners diagonally: 90 settlements over
	# 4096 units is one every four hundred or so, so country is never empty and the roads that connect
	# them are never far off. The old 520-unit radius was sized for a 1600x900 map, which is why a
	# party standing at y 4060 could see nothing but grass.
	var centre := Vector2(WorldChunks.WORLD_SIZE, WorldChunks.WORLD_SIZE) * 0.5
	var sites := WorldSites.build(seed_value)
	var started := Time.get_ticks_usec()
	stage = "Choosing where settlements stand"
	# The survey is the longest single phase and the one that used to say nothing: it takes about a third
	# of the build, so it owns the first third of the bar.
	var chosen := sites.settlement_sites(count, centre, radius, func(part: float) -> void:
		progress = part * 0.35
	)
	var elapsed := float(Time.get_ticks_usec() - started) / 1000.0
	DebugLogger.info("  survey: %.0f ms for %d sites" % [elapsed, chosen.size()], "WorldBuilder")

	var largest: Settlement = null
	var names: Array[String] = []
	placing = chosen.size()
	stage = "Placing settlements and writing their names"
	for i in chosen.size():
		progress = 0.35 + 0.35 * (float(i) / float(maxi(1, chosen.size())))
		var site := chosen[i]
		var position: Vector2 = site["position"]
		var land := sites.world.sample(position)
		var raw := {
			"id": _slug(str(site["name"]), state.settlements.keys()),
			"name": str(site["name"]),
			"type": _settlement_type(str(site["kind"])),
			"owner_faction_id": "house_caldreth",
			"population": _population_for(str(site["kind"]), position),
			"position": [position.x, position.y],
			"description": _describe(str(site["kind"]), land),
			"recruit_pool": _recruits_for(str(site["kind"]), position),
		}
		var settlement := _build_settlement(raw)
		if settlement == null:
			continue
		state.settlements[settlement.id] = settlement
		names.append(settlement.name)
		if largest == null or settlement.population > largest.population:
			largest = settlement

	_build_roads(chosen, state.settlements)

	DebugLogger.info("world generated: %d settlements from seed %d in %.0f ms | %s" % [
		state.settlements.size(), seed_value, elapsed, ", ".join(names)], "WorldBuilder")

	if largest != null:
		state.world_position = largest.position
		state.destination_id = ""
		DebugLogger.info("player party placed at %s" % largest.name, "WorldBuilder")


## Which settlement record a site's kind becomes. Four kinds in, four kinds out: the record used to
## flatten forts and castles into towns, which made the map unable to say what a place was.
static func _settlement_type(kind: String) -> String:
	match kind:
		"fort":
			return Settlement.TYPE_FORT
		"castle":
			return Settlement.TYPE_CASTLE
		"town":
			return Settlement.TYPE_TOWN
		_:
			return Settlement.TYPE_VILLAGE


static func _population_for(kind: String, position: Vector2) -> int:
	var roll := int(absf(sin(position.x * 12.9898 + position.y * 78.233) * 43758.5453)) % 1000
	match kind:
		"town":
			return 1200 + roll
		"fort":
			return 300 + roll / 4
		"castle":
			return 250 + roll / 5
		_:
			return 260 + roll / 2


## A line of prose from the land the site stands on: what it is, and what the ground around it is
## like, which is what the authored descriptions did and what a generated one can honestly do.
static func _describe(kind: String, land: Dictionary) -> String:
	var height := float(land.get("height", 0.5))
	var region := float(land.get("region", 0.5))
	var ground := "on good open country"
	if height < 0.45:
		ground = "low and damp, with the water never far"
	elif height > 0.68:
		ground = "high and bare, where the wind does the talking"
	elif region < 0.5:
		ground = "at the edge of the wild, with few neighbours"
	var what := "A village"
	match kind:
		"town":
			what = "A market town"
		"fort":
			what = "A fort"
		"castle":
			what = "A castle"
	return "%s %s. %s" % [what, ground, _trade_line(kind)]


static func _trade_line(kind: String) -> String:
	match kind:
		"town":
			return "Wagons stop here, which is most of why it exists."
		"fort":
			return "It watches a road, and the road knows it."
		"castle":
			return "Its walls are older than the family that holds them."
		_:
			return "It sells what the fields do not eat."


static func _recruits_for(kind: String, position: Vector2) -> Dictionary:
	var roll := int(absf(sin(position.y * 4.1414 + position.x * 2.7183) * 24680.135)) % 3
	match kind:
		"town":
			return {"peasant_recruit": 4 + roll, "spearman": 2, "archer": 1 + roll}
		"fort", "castle":
			return {"peasant_recruit": 2, "spearman": 2 + roll, "archer": 1}
		_:
			return {"peasant_recruit": 3 + roll}


## A stable id from a name: two settlements may share a word, none may share an id.
static func _slug(name: String, taken: Array) -> String:
	var base := name.to_lower().replace(" ", "_").replace("'", "")
	var candidate := base
	var counter := 2
	while taken.has(candidate):
		candidate = "%s_%d" % [base, counter]
		counter += 1
	return candidate


## Roads as a spanning tree: every settlement reachable, no pointless crossings. Prim's, cheapest
## link first, which on a map of scattered towns is what the roads are for - the shortest thing that
## connects everything rather than a tour that happens to pass through.
func _build_roads(sites: Array[Dictionary], built: Dictionary) -> void:
	if sites.size() < 2:
		return
	var ids: Array[String] = []
	for site in sites:
		var slug_name := _slug(str(site["name"]), [])
		ids.append(slug_name)
	# Sites and settlements were built in the same order, so the ids line up by name.
	var actual: Array[String] = []
	for site in sites:
		var wanted := str(site["name"])
		for key in built.keys():
			if str(built[key].name) == wanted:
				actual.append(str(key))
				break
	if actual.size() != sites.size():
		DebugLogger.warn("roads: %d of %d settlements matched by name" % [actual.size(), sites.size()], "WorldBuilder")
		return
	var joined: Array[int] = [0]
	var remaining: Array[int] = []
	for i in range(1, actual.size()):
		remaining.append(i)
	while not remaining.is_empty():
		var best_from := -1
		var best_to := -1
		var best_distance := INF
		for a in joined:
			for b in remaining:
				var d := WorldSites._wrapped_distance(sites[a]["position"], sites[b]["position"])
				if d < best_distance:
					best_distance = d
					best_from = a
					best_to = b
		if best_to < 0:
			break
		state.roads.append({
			"a": actual[best_from],
			"b": actual[best_to],
			"kind": "road",
		})
		joined.append(best_to)
		remaining.erase(best_to)


func _build_settlement(raw: Dictionary) -> Settlement:
	var settlement := Settlement.new()
	settlement.id = str(raw.get("id", ""))
	if settlement.id.is_empty():
		DebugLogger.error("settlement entry has no id", "WorldBuilder")
		return null
	settlement.name = str(raw.get("name", settlement.id))
	settlement.type = str(raw.get("type", Settlement.TYPE_TOWN))
	settlement.description = str(raw.get("description", ""))
	settlement.position = DataUtils.vec2_from(raw.get("position", [0.0, 0.0]))
	settlement.owner_faction_id = str(raw.get("owner_faction_id", ""))
	settlement.population = int(raw.get("population", 0))
	settlement.market = (raw.get("market", {}) as Dictionary).duplicate(true)
	settlement.last_restock_day = state.clock.day if state.clock != null else 1

	settlement.recruit_pool.clear()
	settlement.recruit_pool_base.clear()
	for key in (raw.get("recruit_pool", {}) as Dictionary).keys():
		var count := int((raw.get("recruit_pool", {}) as Dictionary)[key])
		settlement.recruit_pool[str(key)] = count
		settlement.recruit_pool_base[str(key)] = count
	return settlement


## A brand-new campaign starts the party at the configured starting settlement.
func _place_player_party() -> void:
	if state.world_position != Vector2.ZERO:
		return
	var start_id := config.get_string("world.start_settlement_id", "")
	var start := state.settlement(start_id)
	if start == null and not state.settlements.is_empty():
		start = state.settlements.values()[0] as Settlement
		start_id = start.id
	if start == null:
		return
	state.world_position = start.position
	state.current_settlement_id = start_id
	DebugLogger.info("player party placed at %s" % start.name, "WorldBuilder")


